name: Aurora DSQL Connector for node-postgres Tests

permissions: {}

on:
  push:
    branches: [main]
    paths:
      - "packages/node-postgres/**"
      - ".github/workflows/node-postgres-integration-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/node-postgres/**"
      - ".github/workflows/node-postgres-integration-tests.yml"
  # Give us a button to allow running the workflow on demand for testing.
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      build-version: "20"
      target-versions: ${{ steps.versions.outputs.matrix }}
    steps:
      - id: versions
        run: echo "matrix=[20, 22, 24]" >> $GITHUB_OUTPUT

  create-cluster:
    uses: ./.github/workflows/dsql-cluster-create.yml
    with:
      workflow_name: node-postgres-tests
    secrets:
      AWS_IAM_ROLE: ${{ secrets.AURORA_DSQL_NODEJS_IAM_ROLE }}
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials

  run-tests:
    name: Node-postgres tests
    needs: [setup, create-cluster]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        node-version: ${{ fromJson(needs.setup.outputs.target-versions) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AURORA_DSQL_NODEJS_IAM_ROLE }}
          aws-region: ${{ needs.create-cluster.outputs.region }}

      - name: Run tests
        working-directory: ./packages/node-postgres
        env:
          CLUSTER_ENDPOINT: ${{ needs.create-cluster.outputs.cluster-endpoint }}
          REGION: ${{ needs.create-cluster.outputs.region }}
          IAM_ROLE: $${{ secrets.AURORA_DSQL_NODEJS_IAM_ROLE }}
        run: |
          npm ci
          npm run check
          npm run test

      - name: Run example smoke test
        working-directory: ./packages/node-postgres
        env:
          CLUSTER_ENDPOINT: ${{ needs.create-cluster.outputs.cluster-endpoint }}
          CLUSTER_USER: admin
          REGION: ${{ needs.create-cluster.outputs.region }}
        run: |
          npm run build:prod
          npm link
          cd example
          npm ci
          npm link @aws/aurora-dsql-node-postgres-connector
          npm run test

  delete-cluster:
    if: always() && needs.create-cluster.result == 'success'
    needs: [create-cluster, run-tests]
    uses: ./.github/workflows/dsql-cluster-delete.yml
    with:
      cluster-id: ${{ needs.create-cluster.outputs.cluster-id }}
      region: ${{ needs.create-cluster.outputs.region }}
    secrets:
      AWS_IAM_ROLE: ${{ secrets.AURORA_DSQL_NODEJS_IAM_ROLE }}
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials
